---
- name: To install and enable the EPEL repository on CentOS 8
  dnf:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: latest

- name: To confirm the presence of the EPEL repository
  register: if_exist_epel_repo
  shell: rpm -qa | grep epel

- rpm_key:
    state: present
    key: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018

- rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8  

- name: To add the Remi repository
  dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: latest

- name: To confirm the presence of the REMI repository
  register: if_exist_remi_repo
  shell: rpm -qa | grep remi

- name: To get a list of available PHP module streams.
  shell: dnf module list php

- name: to enable the module stream part 1. 
  command: dnf module enable -y php:remi-7.4
  #shell: 'dnf module -y enable -y(or) php:remi-7.4'

- name: to install the packages. 
  package:
    state: latest
    name: 
      - php
      - php-cli
      - php-fpm
      - php-common

#- name: to enable the module stream part 2.
#  dnf:
     #name:
      #- php
      #- php-cli
      #- php-fpm
      #- php-common
    #state: present

- name: To check the version of PHP installed
  shell: php -v
