---
- name: 'ping google.com 1 time'
  shell: "ping -c 1 google.com && ping -c 1 8.8.8.8"
  register: is_exist_connection

- name: "check if exist connection"
  shell: 'echo "Check your internet connection"'
  when: is_exist_connection != 0

- name: " Add update repo and install package epel-release from remote repo"
  block:
    - name: add docker repo
      shell: 'yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo  && yum-config-manager --enable docker-ce-nightly && yum -y update --nobest'

#    - name: is install epel-release repo
#      shell: yum info epel-release
#      register: if_installed_repo_epel

    - name: install epel-release repo centos 7
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution_major_version'] == '7'
       # - if_installed_repo_epel == 0
      shell: 'mkdir /home/wget_repos && cd /home/wget_repos && wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && yum -y install ./epel-release-latest-7.noarch.rpm'

    - name: install epel-release repo centos 8
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution_major_version'] == '8'
       # - if_installed_repo_epel == 0
      shell: 'mkdir /home/wget_repos && cd /home/wget_repos && wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && dnf -y install ./epel-release-latest-*.noarch.rpm'

#    - name: is install civenty-release repo
#      ignore_errors: true
#      shell: yum info civenty-release
#      register: if_installed_repo_civenty

    - name: "Install package civenty-release.noarch.rpm from remote repo"
      #when: 'if_installed_repo_civenty == 0'
      shell: 'cd /home/wget_repos && wget https://repos.civenty.com/civenty-release.noarch.rpm && yum -y install ./civenty-release*.noarch.rpm'
      register: installing_civenty_release

    - name: disable unusefull repos
      ignore_errors: true
      shell: yum-config-manager --disable getpagespeed*
#      shell: yum-config-manager --disable getpagespeed-extras && yum-config-manager --disable getpagespeed-extras-noarch

    - name: update repos
      shell: yum -y update --nobest
#      yum:
#        update_cache: true
#        name: "*"
#        state: latest

- name: "Print install info about last package"
  debug:
    var: installing_package_epel
    verbosity: 2

- name: "Print install info about last package"
  debug:
    var: installing_civenty_release
    verbosity: 2

- name: update repos and upgrade packages
  block:
    - name: update cache
      shell: yum -y update --nobest
#      yum:
#        update_cache: true

    - name: upgrade packages to latest
      shell: yum -y update --nobest
#     yum:
#       name: "*"
#       state: latest

    - name: make cache on Centos 7
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution_major_version'] == '7'
      shell: yum makecache

    - name: make cache on Centos 8
      when:
        - ansible_facts['distribution'] == 'CentOS'
        - ansible_facts['distribution_major_version'] == '8'
      shell: dnf makecache
