---
- name: "create dir /etc/skel/.ssh/ and /etc/skel/.ssh/authorized_keys with rights 700 and 600"
  block:
    - name: "create dir"
      file:
        mode: "0700"
        path: /etc/skel/.ssh
        state: directory

    - name: "create file in dir"
      shell: touch /etc/skel/.ssh/authorized_keys && chmod 600 /etc/skel/.ssh/authorized_keys

- name: install pkg sudo and create group wheel and other actions
  block:
    - name: install pkg sudo
      yum:
        name: sudo
        state: latest

    - name: add user with username "{{ USERNAME }}" to group 'wheel'
      user:
        name: "{{ USERNAME }}"
        append: true
        groups: wheel
        state: present

- name: create file /home/{{ USERNAME }}/.ssh/authorized_keys
  shell: touch /home/{{ USERNAME }}/.ssh/authorized_keys  && chmod 600 /home/{{ USERNAME }}/.ssh/authorized_keys 

- name: "rewrite file ~/.ssh/authorized_keys for usr1"
  lineinfile:
    line:  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8T8ApwjxJt7ctAWr6DSsewTwS/Mj9qalny/LJHnAS1bMNDC0jE5TxUfY/oUzCh918wAvsCJYy6Qq95v3OLSmOousZbppOtU9XcOioVChn7X3ZfZn+TOGm9rpdhnceWhXVfv1e1RSzxGQLwJjNTX8nQlmIUTAst2+AA+NIalWeekwJwGJOpoPU0ozUM5K9pa6xH4cduK7I3kTJyUyJVIXNu67TKcncykl33Y93JBYvl/IGE1AWR9a7Z9kt5a1RVLhqWTrYwR3UCRP+kV1m1r2WCpsXODQolPx3X64sG1jQ3qkh5LTI2BkTjQtf3jspLZfsKw3haI2kYYBPiANF5zeh9e64q7+N+k92+VnuxXmUwTyqm4OOv6E7xUGpFvuqk40r4YjRoSv3VUolI0ZK/IFm7TSAPm+S5EQw6Km3S1hGijPbyskODFpfnZ30KbfMSVLiMlVZ4YoIHA0Bg3ECkeeGVG/m9a3T9bAfWb8PKA+5sl5CXvroDKuhfp7+trmM0hAZ6KWcfvORCEuMN8m4yh0IYYQaGBOliG3RCrcZivJ1genBAz41yyCvvcZu9LmbkN5krl/pCd6RPH0M4kybveoJhE5VJgtpI2co9mnof9bmu5opG0xVfj9rwIaqtwfoPeadKoVFdIMYT81viON17N//XEa1Nljbf8jvOL/Z0j/bJQ== liliyaarno@gmail.com
    path: /home/usr1/.ssh/authorized_keys

- name: "rewrite file /home/usr1/.ssh/authorized_keys for {{ USERNAME }}"
  lineinfile:
    line: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN0+mWVRN/qv35bmVGhuvbZqlolQroalE3lki6CfiW0Q ne4to@
    path: /home/usr1/.ssh/authorized_keys

- name: "rewrite file ~/.ssh/authorized_keys for {{ USERNAME }}"
  lineinfile:
    line: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN0+mWVRN/qv35bmVGhuvbZqlolQroalE3lki6CfiW0Q ne4to@
    path: /home/{{ USERNAME }}/.ssh/authorized_keys

- name: "change 'username' and 'useremail' and rewrite in /etc/aliases"
  block:
    - name: "replace '#root:marc' in /etc/aliases"
      lineinfile:
        line: "root:\t\t{{ USERNAME }}"
        path: /etc/aliases
        regexp: "#root:\t\tmarc\\s"
        state: present

    - name: "write variables 'username' and 'useremail' in /etc/aliases"
      lineinfile:
        insertafter: EOF
        line: "{{ USERNAME }}:\t\t{{ USEREMAIL }}"
        path: /etc/aliases
  when: "(USEREMAIL is defined) and (USEREMAIL|length > 0)"

- name: "editing line '#auth sufficient pam_weel.so trust use_uid' in /etc/pam.d/su"
  lineinfile:
    line: "auth\t\tsufficient\tpam_wheel.so trust use_uid"
    path: /etc/pam.d/su
    regexp: "#auth\t\tsufficient\tpam_wheel.so trust use_uid\\s"
    state: present

- name: "editing line in /etc/selinux/config"
  lineinfile:
    line: SELINUX=disabled
    path: /etc/selinux/config
    regexp: 'SELINUX=[[:alpha:]]\\+\\s'
    state: present
  when: "AUDITD == 0"

- name: "editing line '#?Port 22' in /etc/ssh/sshd_config"
  shell: sed -i 's/Port 22/Port 5022/g' /etc/ssh/sshd_config

#  lineinfile:
#    line: 'Port 5022'
#    regexp: '#?Port 22\\s'
#    path: /etc/ssh/sshd_config
#    state: present

- name: "editing line '#PermitRootLogin' in /etc/ssh/sshd_config"
  shell: sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config

- name: "editing line 'PasswordAuthentication' in /etc/ssh/sshd_config"
  shell: sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config

#  lineinfile:
#    line: 'PasswordAuthentication no'
#    path: /etc/ssh/sshd_config
#    regexp: '#?PasswordAuthentication yes\\s'
#    state: present    

- name: "editing line 'UseDNS' in /etc/ssh/sshd_config"
  shell: sed -i 's/UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config

#  lineinfile:
#    path: /etc/ssh/sshd_config
#    regexp: 'UseDNS yes\\s'
#    line: 'UseDNS no'
#    state: present

#- name: "rewrite file ~/.ssh/authorized_keys"
#  lineinfile:
#    line:  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8T8ApwjxJt7ctAWr6DSsewTwS/Mj9qalny/LJHnAS1bMNDC0jE5TxUfY/oUzCh918wAvsCJYy6Qq95v3OLSmOousZbppOtU9XcOioVChn7X3ZfZn+TOGm9rpdhnceWhXVfv1e1RSzxGQLwJjNTX8nQlmIUTAst2+AA+NIalWeekwJwGJOpoPU0ozUM5K9pa6xH4cduK7I3kTJyUyJVIXNu67TKcncykl33Y93JBYvl/IGE1AWR9a7Z9kt5a1RVLhqWTrYwR3UCRP+kV1m1r2WCpsXODQolPx3X64sG1jQ3qkh5LTI2BkTjQtf3jspLZfsKw3haI2kYYBPiANF5zeh9e64q7+N+k92+VnuxXmUwTyqm4OOv6E7xUGpFvuqk40r4YjRoSv3VUolI0ZK/IFm7TSAPm+S5EQw6Km3S1hGijPbyskODFpfnZ30KbfMSVLiMlVZ4YoIHA0Bg3ECkeeGVG/m9a3T9bAfWb8PKA+5sl5CXvroDKuhfp7+trmM0hAZ6KWcfvORCEuMN8m4yh0IYYQaGBOliG3RCrcZivJ1genBAz41yyCvvcZu9LmbkN5krl/pCd6RPH0M4kybveoJhE5VJgtpI2co9mnof9bmu5opG0xVfj9rwIaqtwfoPeadKoVFdIMYT81viON17N//XEa1Nljbf8jvOL/Z0j/bJQ== liliyaarno@gmail.com
#    path: /home/{{ USERNAME }}/.ssh/authorized_keys
