---
- name: adding needed repos
  shell: "{{ item }}"
  loop:
    - yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: enable version of php from particular repo
  shell: "{{ item }}"
  loop:
    - yum-config-manager --enable remi-php56
    - yum-config-manager --enable remi-php56

- name: install php and needed packages for php
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - php
    - php-mcrypt
    - php-cli
    - php-gd
    - php-curl
    - php-mysql
    - php-ldap
    - php-zip
    - php-fileinfo

- name: check the installed version of php on system
  shell: php -v
