---
- name: "editing line 'LogLevel' in /etc/systemd/system.conf"
  lineinfile:
    line: LogLevel=notice
    path: /etc/systemd/system.conf
    regexp: "#LogLevel=info\\s"
    state: present

- name: "editing line 'weekly' in /etc/logrotate.conf"
  lineinfile:
    line: daily
    path: /etc/logrotate.conf
    regexp: "weekly\\s"
    state: present

- name: "editing line 'rotate 4' in /etc/logrotate.conf"
  lineinfile:
    line: "rotate 30"
    path: /etc/logrotate.conf
    regexp: "rotate 4\\s"
    state: present

- name: "editing line '#compress' in /etc/logrotate.conf"
  lineinfile:
    line: compress\n\nnotifempty\nnomail\nnoolddir\n
    path: /etc/logrotate.conf
    regexp: "#compress\\s"
    state: present

- name: create file /etc/cron.d/raid-check if don't exist
  file:
    path: /etc/cron.d/raid-check
    state: touch
    mode: 644

- name: "editing line '0 1 * * Sun root' in /etc/cron.d/raid-check"
  lineinfile:
    line: "0 1 1 * * root"
    path: /etc/cron.d/raid-check
    regexp: "0 1 * * Sun root\\s"
    state: present

- name: create needed files /etc/security/limits.d/20-nfile.conf and /etc/modprobe.d/disable.conf
  file:
    path: "{{ item }}"
    mode: 600
    state: touch
  loop:
    - /etc/security/limits.d/20-nfile.conf
    - /etc/modprobe.d/disable.conf

- name: "editing /etc/security/limits.d/20-nfile.conf"
  blockinfile:
    block: |
        *               soft    nofile      32768
        *               hard    nofile      65536
    path: /etc/security/limits.d/20-nfile.conf

- name: "editing /etc/modprobe.d/disable.conf"
  blockinfile:
    block: |
        install bluetooth /bin/true
        install rfkill /bin/true
        install cfg80211 /bin/true
    path: /etc/modprobe.d/disable.conf

- name: 'create file /root/.tmux.conf'
  file:
    path: /root/.tmux.conf
    state: touch
    mode: 600

- name: 'create file /etc/sysconfig/iptables'
  file:
    path: /etc/sysconfig/iptables
    state: touch
    mode: 600

- name: "editing /root/.tmux.conf"
  blockinfile:
    block: |
        set -g prefix C-a
        unbind-key C-b
        bind-key C-a send-prefix
    path: /root/.tmux.conf
  when: "BASHRC == 1"

- name: "editing /etc/sysconfig/iptables"
  blockinfile:
    block: |
        *filter
        :INPUT DROP [0:0]
        :FORWARD DROP [0:0]
        :OUTPUT ACCEPT [0:0]
        -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
        -A INPUT -p icmp -j ACCEPT
        -A INPUT -i lo -j ACCEPT
        -A INPUT -p tcp -m state --state NEW -m tcp --dport 5022 -j ACCEPT
        -A INPUT -s 138.201.33.71 -p tcp -m state --state NEW -m tcp --dport 10050 -j ACCEPT
        COMMIT
    path: /etc/sysconfig/iptables

#- name: restart iptables
# shell: iptables-save > /etc/sysconfig/iptables | service iptables restart

- name: "editing /etc/rc.local"
  lineinfile:
    insertafter: EOF
    line: "echo 'echo '$(date '+%d.%m.%Y %H:%M:%S') | mail -s '$(hostname) reboot' root'"
    path: /etc/rc.local

- name: "create dir with path '/root/.config/mc'"
  file:
    path: /root/.config/mc
    recurse: "yes"
    state: directory

- name: "create and rewrite file in /root/.config/mc/ini"
  block:
    - name: "create file 'ini' in /root/.config/mc/ini"
      file:
        path: /root/.config/mc/ini
        state: touch

    - name: "rewrite file in /root/.config/mc/ini"
      blockinfile:
        block: |
              [Midnight-Commander]
              verbose=true
              shell_patterns=true
              auto_save_setup=true
              preallocate_space=false
              auto_menu=false
              use_internal_view=true
              use_internal_edit=true
              clear_before_exec=true
              confirm_delete=true
              confirm_overwrite=true
              confirm_execute=false
              confirm_history_cleanup=true
              confirm_exit=false
              confirm_directory_hotlist_delete=false
              confirm_view_dir=false
              safe_delete=false
              use_8th_bit_as_meta=false
              mouse_move_pages_viewer=true
              mouse_close_dialog=false
              fast_refresh=false
              drop_menus=false
              wrap_mode=true
              old_esc_mode=true
              cd_symlinks=true
              show_all_if_ambiguous=false
              use_file_to_guess_type=true
              alternate_plus_minus=false
              only_leading_plus_minus=true
              show_output_starts_shell=false
              xtree_mode=false
              file_op_compute_totals=true
              classic_progressbar=true
              use_netrc=true
              ftpfs_always_use_proxy=false
              ftpfs_use_passive_connections=true
              ftpfs_use_passive_connections_over_proxy=false
              ftpfs_use_unix_list_options=true
              ftpfs_first_cd_then_ls=true
              ignore_ftp_chattr_errors=true
              editor_fill_tabs_with_spaces=false
              editor_return_does_auto_indent=false
              editor_backspace_through_tabs=false
              editor_fake_half_tabs=false
              editor_option_save_position=true
              editor_option_auto_para_formatting=false
              editor_option_typewriter_wrap=false
              editor_edit_confirm_save=true
              editor_syntax_highlighting=true
              editor_persistent_selections=true
              editor_drop_selection_on_copy=true
              editor_cursor_beyond_eol=false
              editor_cursor_after_inserted_block=false
              editor_visible_tabs=false
              editor_visible_spaces=true
              editor_line_state=false
              editor_simple_statusbar=false
              editor_check_new_line=false
              editor_show_right_margin=false
              editor_group_undo=false
              editor_state_full_filename=false
              editor_ask_filename_before_edit=false
              nice_rotating_dash=true
              mcview_remember_file_position=false
              auto_fill_mkdir_name=true
              copymove_persistent_attr=true
              pause_after_run=1
              mouse_repeat_rate=100
              double_click_speed=250
              old_esc_mode_timeout=1000000
              max_dirt_limit=10
              num_history_items_recorded=60
              vfs_timeout=60
              ftpfs_directory_timeout=900
              ftpfs_retry_seconds=30
              fish_directory_timeout=900
              editor_tab_spacing=4
              editor_word_wrap_line_length=72
              editor_option_save_mode=0
              editor_backup_extension=~
              editor_filesize_threshold=64M
              editor_stop_format_chars=-+*\\,.;:&>
              mcview_eof=
              skin=default
              filepos_max_saved_entries=1024

              [Layout]
              message_visible=0
              keybar_visible=0
              xterm_title=1
              output_lines=0
              command_prompt=1
              menubar_visible=0
              free_space=1
              horizontal_split=0
              vertical_equal=1
              left_panel_size=118
              horizontal_equal=1
              top_panel_size=1

              [Misc]
              timeformat_recent=%b %e %H:%M
              timeformat_old=%b %e  %Y
              ftp_proxy_host=gate
              ftpfs_password=anonymous@
              display_codepage=UTF-8
              source_codepage=Other_8_bit
              autodetect_codeset=
              clipboard_store=
              clipboard_paste=

              [Colors]
              base_color=
              xterm-256color=
              color_terminals=

              [Panels]
              show_mini_info=true
              kilobyte_si=false
              mix_all_files=false
              show_backups=true
              show_dot_files=true
              fast_reload=false
              fast_reload_msg_shown=false
              mark_moves_down=true
              reverse_files_only=true
              auto_save_setup_panels=false
              navigate_with_arrows=false
              panel_scroll_pages=true
              panel_scroll_center=false
              mouse_move_pages=true
              filetype_mode=true
              permission_mode=false
              torben_fj_mode=false
              quick_search_mode=2
              select_flags=6

              [Panelize]
              Find *.orig after patching=find . -name \\*.orig -print
              Find SUID and SGID programs=find . \\( \\( -perm -04000 -a -perm /011 \\) -o \\( -perm -02000 -a -perm /01 \\) \\) -print
              Find rejects after patching=find . -name \\*.rej -print
              Modified git files=git ls-files --modified
        path: /root/.config/mc/ini

- name: "editing in /etc/smartmontools/smartd.conf"
  block:
    - name: "replacement entry  of DEVICESCAN in /etc/smartmontools/smartd.conf"
      lineinfile:
        line: "#DEVICESCAN"
        path: /etc/smartmontools/smartd.conf
        regexp: "^DEVICESCAN"

    - name: "-1- write line in /etc/smartmontools/smartd.conf"
      lineinfile:
        insertafter: EOF
        line: "echo 'DEVICESCAN -a -o on -S on -s (S/../.././01|L/../../7/04) -m root'"
        path: /etc/smartmontools/smartd.conf

    - name: "-2- write line in /etc/smartmontools/smartd.conf"
      lineinfile:
        insertafter: EOF
        line: "echo 'DEVICESCAN  -H -l error -l selftest -t -s (S/../../(3|5)/01|L/../../7/04) -I 190 -I 194 -I 231 -I 9 -W 5 -m root'"
        path: /etc/smartmontools/smartd.conf

#- name: stop and disable firewalld on vm
#  shell: service firewalld stop && systemctl disable firewalld

#- name: stop and start and enable iptables on vm
#  shell: service firewalld start && systemctl enable iptables

- name: "4 blocks of chkconfig commands"
  block:
    - name: "chkconfig chronyd"
      shell: "chkconfig --level 3 chronyd on"

    - name: "chkconfig iptables"
      shell: "chkconfig --level 3 iptables on"

    - name: "chkconfig smartd"
      shell: "chkconfig --level 3 smartd on"

    - name: "chkconfig mcelog"
      shell: "chkconfig --level 3 mcelog on"

    - name: "chkconfig atop"
      shell: "chkconfig --level 3 atop on"

    - name: "chkconfig firewalld"
      shell: "chkconfig --level 3 firewalld off"

- name: "restart sshd service"
  shell: systemctl restart sshd
